### ISSUE TITLE
Initial motor offsets seem to be changing

### ISSUE THREAD

**Issue by mikeblanton** [dirtbikerxz/BaseTalonFXSwerve#24]
Something odd we're experiencing, it appears our motor offsets are changing every time we reset the robot or deploy code. It's only off by a few degrees each time, but it affects wheel positioning. Does anyone have any thoughts on how to troubleshoot what might be happening?

**Comment by dirtbikerxz** [comment]
Have you ensure the encoder magnets have been properly loctited/glued in place?

Also if you can provide a link to your code that would be helpful.

**Comment by mikeblanton** [comment]
I don't think the magnets have been glued. Let me have the team check into that. The code is the Team 364 code with just the configurations updated per the docs - no other customizations yet.

**Comment by dirtbikerxz** [comment]
> I don't think the magnets have been glued. 

Ya, if that's the case that is definitely the cause of the issue.

From the [assembly guide](https://drive.google.com/file/d/1FBRBFIMH0lY_B9EJXfujerzmCWr5-Bwu/view?pli=1):
![image](https://github.com/Team364/BaseFalconSwerve/assets/11358810/3b7e3aec-3962-4f80-b49a-8776e6086b30)
(SDS recomends Loctite 609, we personally just used super glue since we had it on hand and had no issues)
